### ISSUE TITLE
is that nerf captured mesh?

### ISSUE THREAD

**Issue by flankechen** [LanHao0/myArtWorksIn3D#21]
is that nerf captured mesh and point cloud?

**Comment by LanHao0** [comment]
yes! some are generated by NeRF!
I put them in blender to make them cooler!

**Comment by flankechen** [comment]
So, how you translate nerf to grid mesh?
I was looking for some direct nerf rendering "real world" scene in threejs.
tfjs should be able to forward the nerf mlp layers and output a rgb texture, fps is a problem, but it should work.

**Comment by LanHao0** [comment]
> So, how you translate nerf to grid mesh? I was looking for some direct nerf rendering "real world" scene in threejs. tfjs should be able to forward the nerf mlp layers and output a rgb texture, fps is a problem, but it should work.

please checkout this repo, https://github.com/NVlabs/instant-ngp
you can save the mesh directly from the GUI.

**Comment by LanHao0** [comment]
if no further questions, this issue will be closed.
